
# site name and description, displayed in the header
name: Alan Porter
description: My Wiki

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


url: "http://AlanPorter.com/wiki"
baseurl: "/wiki"

categoryList: []
relative_permalinks: false

# markup
markdown: redcarpet
highlighter: pygments
permalink: /:title/

# Exclude these files from your production _site
exclude:
  - preprocess.sh
  - post-update.hook
  - LICENSE
  - README.md

